@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam ClassAttributeFontColor #FFFFFF

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniquePersonList

UniqueTagList -right-> "*" Tag
UniquePersonList -right-> Person

Person -up-> "*" Tag

class Person {
  clientId: ClientId
  name: Name
  gender: Gender
  dateOfBirth: DateOfBirth
  phone: Phone
  email: Email
  address: Address
  location: Location
  height: Height
  weight: Weight
  bodyFatPercentage: BodyFatPercentage
  plan: Plan
  rate: Rate
  status: Status
  note: Note
  tags: Tag[]
}

show Person members
@enduml
