@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":StatusCommandParser" as StatusCommandParser LOGIC_COLOR
participant "s:StatusCommand" as StatusCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
participant "p:Person" as Person MODEL_COLOR
end box

[-> LogicManager : execute("status 1 s/inactive")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("status 1 s/inactive")
activate AddressBookParser

create StatusCommandParser
AddressBookParser -> StatusCommandParser
activate StatusCommandParser

StatusCommandParser --> AddressBookParser
deactivate StatusCommandParser

AddressBookParser -> StatusCommandParser : parse("1 s/inactive")
activate StatusCommandParser

create StatusCommand
StatusCommandParser -> StatusCommand
activate StatusCommand

StatusCommand --> StatusCommandParser :
deactivate StatusCommand

StatusCommandParser --> AddressBookParser : s
deactivate StatusCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
StatusCommandParser -[hidden]-> AddressBookParser
destroy StatusCommandParser

AddressBookParser --> LogicManager : s
deactivate AddressBookParser

LogicManager -> StatusCommand : execute(m)
activate StatusCommand

StatusCommand -> Model : getFilteredPersonList()
activate Model

Model --> StatusCommand : lastShownList
deactivate Model

StatusCommand -> Model : lastShownList.get(index)
activate Model

Model --> StatusCommand : personToEdit
deactivate Model

StatusCommand -> Person : withStatus(inactive)
activate Person

Person --> StatusCommand : editedPerson
deactivate Person

StatusCommand -> Model : setPerson(personToEdit, editedPerson)
activate Model

Model --> StatusCommand
deactivate Model

create CommandResult
StatusCommand -> CommandResult
activate CommandResult

CommandResult --> StatusCommand
deactivate CommandResult

StatusCommand --> LogicManager : r
deactivate StatusCommand

[<-- LogicManager
deactivate LogicManager
@enduml
